-- MySQL Script generated by MySQL Workbench
-- Sat Jun 15 19:16:33 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema classroom
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `classroom` ;

-- -----------------------------------------------------
-- Schema classroom
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `classroom` DEFAULT CHARACTER SET utf8 ;
USE `classroom` ;

-- -----------------------------------------------------
-- Table `classroom`.`department`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `classroom`.`department` ;

CREATE TABLE IF NOT EXISTS `classroom`.`department` (
  `dept_name` VARCHAR(20) NOT NULL,
  `building` VARCHAR(15) NULL DEFAULT NULL,
  `budget` DECIMAL(12,2) NULL DEFAULT NULL,
  PRIMARY KEY (`dept_name`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `classroom`.`classroom`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `classroom`.`classroom` ;

CREATE TABLE IF NOT EXISTS `classroom`.`classroom` (
  `room_number` INT NULL AUTO_INCREMENT,
  `capacity` DECIMAL(4,0) NULL DEFAULT NULL,
  `department_dept_name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`room_number`, `department_dept_name`),
  INDEX `fk_classroom_department1_idx` (`department_dept_name` ASC),
  CONSTRAINT `fk_classroom_department1`
    FOREIGN KEY (`department_dept_name`)
    REFERENCES `classroom`.`department` (`dept_name`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `classroom`.`course`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `classroom`.`course` ;

CREATE TABLE IF NOT EXISTS `classroom`.`course` (
  `course_id` VARCHAR(8) NOT NULL,
  `title` VARCHAR(50) NULL DEFAULT NULL,
  `credits` DECIMAL(2,0) NULL DEFAULT NULL,
  `department_dept_name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`course_id`),
  INDEX `fk_course_department1_idx` (`department_dept_name` ASC),
  CONSTRAINT `fk_course_department1`
    FOREIGN KEY (`department_dept_name`)
    REFERENCES `classroom`.`department` (`dept_name`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `classroom`.`instructor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `classroom`.`instructor` ;

CREATE TABLE IF NOT EXISTS `classroom`.`instructor` (
  `instructor_id` INT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL,
  `salary` DECIMAL(8,2) NULL DEFAULT NULL,
  `department_dept_name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`instructor_id`),
  INDEX `fk_instructor_department1_idx` (`department_dept_name` ASC),
  CONSTRAINT `fk_instructor_department1`
    FOREIGN KEY (`department_dept_name`)
    REFERENCES `classroom`.`department` (`dept_name`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `classroom`.`prereq`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `classroom`.`prereq` ;

CREATE TABLE IF NOT EXISTS `classroom`.`prereq` (
  `course_id` VARCHAR(8) NOT NULL,
  `prereq_id` VARCHAR(8) NOT NULL,
  PRIMARY KEY (`course_id`, `prereq_id`),
  INDEX `prereq_id` (`prereq_id` ASC),
  CONSTRAINT `prereq_ibfk_1`
    FOREIGN KEY (`course_id`)
    REFERENCES `classroom`.`course` (`course_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `prereq_ibfk_2`
    FOREIGN KEY (`prereq_id`)
    REFERENCES `classroom`.`course` (`course_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `classroom`.`section`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `classroom`.`section` ;

CREATE TABLE IF NOT EXISTS `classroom`.`section` (
  `sec_id` VARCHAR(8) NOT NULL,
  `semester` INT NOT NULL,
  `program` VARCHAR(10) NOT NULL,
  `time_slot_id` VARCHAR(4) NOT NULL,
  `department` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`sec_id`, `semester`, `program`),
  INDEX `fk_section_classroom1_idx` (`department` ASC),
  CONSTRAINT `fk_section_classroom1`
    FOREIGN KEY (`department`)
    REFERENCES `classroom`.`classroom` (`department_dept_name`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `classroom`.`student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `classroom`.`student` ;

CREATE TABLE IF NOT EXISTS `classroom`.`student` (
  `stu_reg` VARCHAR(15) NOT NULL,
  `name` VARCHAR(20) NOT NULL,
  `tot_cred` DECIMAL(3,0) NULL,
  `department_dept_name` VARCHAR(20) NOT NULL,
  `section_sec_id` VARCHAR(8) NOT NULL,
  `section_semester` INT NOT NULL,
  `section_program` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`stu_reg`),
  INDEX `fk_student_department1_idx` (`department_dept_name` ASC),
  INDEX `fk_student_section1_idx` (`section_sec_id` ASC, `section_semester` ASC, `section_program` ASC),
  CONSTRAINT `fk_student_department1`
    FOREIGN KEY (`department_dept_name`)
    REFERENCES `classroom`.`department` (`dept_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_student_section1`
    FOREIGN KEY (`section_sec_id` , `section_semester` , `section_program`)
    REFERENCES `classroom`.`section` (`sec_id` , `semester` , `program`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `classroom`.`teaches`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `classroom`.`teaches` ;

CREATE TABLE IF NOT EXISTS `classroom`.`teaches` (
  `instructor_id` INT NOT NULL,
  `course_id` VARCHAR(8) NOT NULL,
  `sec_id` VARCHAR(8) NOT NULL,
  `semester` INT NOT NULL,
  `year` DECIMAL(4,0) NOT NULL,
  PRIMARY KEY (`instructor_id`, `course_id`, `sec_id`, `semester`, `year`),
  INDEX `course_id` (`course_id` ASC, `sec_id` ASC, `semester` ASC, `year` ASC),
  CONSTRAINT `teaches_ibfk_1`
    FOREIGN KEY (`sec_id` , `semester` , `year`)
    REFERENCES `classroom`.`section` (`sec_id` , `semester` , `program`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `teaches_ibfk_2`
    FOREIGN KEY (`instructor_id`)
    REFERENCES `classroom`.`instructor` (`instructor_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `classroom`.`time_slot`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `classroom`.`time_slot` ;

CREATE TABLE IF NOT EXISTS `classroom`.`time_slot` (
  `time_slot_id` INT NULL AUTO_INCREMENT,
  `day` VARCHAR(12) NOT NULL,
  `start` VARCHAR(7) NOT NULL,
  `end` VARCHAR(7) NOT NULL,
  `section_sec_id` VARCHAR(8) NOT NULL,
  `section_semester` INT NOT NULL,
  `section_year` DECIMAL(4,0) NOT NULL,
  PRIMARY KEY (`time_slot_id`, `day`),
  INDEX `fk_time_slot_section1_idx` (`section_sec_id` ASC, `section_semester` ASC, `section_year` ASC),
  CONSTRAINT `fk_time_slot_section1`
    FOREIGN KEY (`section_sec_id` , `section_semester` , `section_year`)
    REFERENCES `classroom`.`section` (`sec_id` , `semester` , `program`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `classroom`.`advisor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `classroom`.`advisor` ;

CREATE TABLE IF NOT EXISTS `classroom`.`advisor` (
  `stu_reg` VARCHAR(15) NOT NULL,
  `instructor_id` INT NOT NULL,
  PRIMARY KEY (`stu_reg`, `instructor_id`),
  INDEX `fk_student_has_instructor_instructor1_idx` (`instructor_id` ASC),
  INDEX `fk_student_has_instructor_student1_idx` (`stu_reg` ASC),
  CONSTRAINT `fk_student_has_instructor_student1`
    FOREIGN KEY (`stu_reg`)
    REFERENCES `classroom`.`student` (`stu_reg`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_student_has_instructor_instructor1`
    FOREIGN KEY (`instructor_id`)
    REFERENCES `classroom`.`instructor` (`instructor_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `classroom`.`takes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `classroom`.`takes` ;

CREATE TABLE IF NOT EXISTS `classroom`.`takes` (
  `student_stu_reg` VARCHAR(15) NOT NULL,
  `course_course_id` VARCHAR(8) NOT NULL,
  PRIMARY KEY (`student_stu_reg`, `course_course_id`),
  INDEX `fk_student_has_course_course1_idx` (`course_course_id` ASC),
  INDEX `fk_student_has_course_student1_idx` (`student_stu_reg` ASC),
  CONSTRAINT `fk_student_has_course_student1`
    FOREIGN KEY (`student_stu_reg`)
    REFERENCES `classroom`.`student` (`stu_reg`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_student_has_course_course1`
    FOREIGN KEY (`course_course_id`)
    REFERENCES `classroom`.`course` (`course_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
