/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dbproject;

import javax.swing.*;

/**
 * @author Mutahhar BM
 */
public class InsertTimeSlots extends javax.swing.JFrame {
    FromDB instanceOfDB = new FromDB();
    TableUI table = new TableUI();

    /**
     * Creates new form InsertStudent
     */
    public InsertTimeSlots() {
        initComponents();
        instanceOfDB.setConnection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        studentPane = new javax.swing.JPanel();
        studentRegLabel = new javax.swing.JLabel();
        timeSlotId = new javax.swing.JTextField();
        studentPane2 = new javax.swing.JPanel();
        studentNameLabel = new javax.swing.JLabel();
        day = new javax.swing.JTextField();
        studentPane8 = new javax.swing.JPanel();
        studentNameLabel3 = new javax.swing.JLabel();
        startTime = new javax.swing.JTextField();
        studentPane9 = new javax.swing.JPanel();
        studentNameLabel4 = new javax.swing.JLabel();
        endTime = new javax.swing.JTextField();
        insertButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        listButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Time Slot");
        setAlwaysOnTop(true);

        studentPane.setLayout(null);

        studentRegLabel.setText("TimeSlot Id:");
        studentPane.add(studentRegLabel);
        studentRegLabel.setBounds(0, 14, 80, 14);

        timeSlotId.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        studentPane.add(timeSlotId);
        timeSlotId.setBounds(80, 11, 100, 28);

        studentNameLabel.setText("Day:");

        javax.swing.GroupLayout studentPane2Layout = new javax.swing.GroupLayout(studentPane2);
        studentPane2.setLayout(studentPane2Layout);
        studentPane2Layout.setHorizontalGroup(
                studentPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(studentPane2Layout.createSequentialGroup()
                                .addComponent(studentNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(day, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );
        studentPane2Layout.setVerticalGroup(
                studentPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(studentPane2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(studentPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(studentNameLabel)
                                        .addComponent(day, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        studentNameLabel3.setText("Start Time:");

        javax.swing.GroupLayout studentPane8Layout = new javax.swing.GroupLayout(studentPane8);
        studentPane8.setLayout(studentPane8Layout);
        studentPane8Layout.setHorizontalGroup(
                studentPane8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(studentPane8Layout.createSequentialGroup()
                                .addComponent(studentNameLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(startTime, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        studentPane8Layout.setVerticalGroup(
                studentPane8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(studentPane8Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(studentPane8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(studentNameLabel3)
                                        .addComponent(startTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        studentNameLabel4.setText("End Time:");

        javax.swing.GroupLayout studentPane9Layout = new javax.swing.GroupLayout(studentPane9);
        studentPane9.setLayout(studentPane9Layout);
        studentPane9Layout.setHorizontalGroup(
                studentPane9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(studentPane9Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(studentNameLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(endTime, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );
        studentPane9Layout.setVerticalGroup(
                studentPane9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(studentPane9Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(studentPane9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(studentNameLabel4)
                                        .addComponent(endTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        insertButton.setText("Insert");
        insertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertButtonActionPerformed(evt);
            }
        });

        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        listButton.setText("List");
        listButton.setMaximumSize(new java.awt.Dimension(65, 28));
        listButton.setMinimumSize(new java.awt.Dimension(65, 28));
        listButton.setPreferredSize(new java.awt.Dimension(65, 28));
        listButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(studentPane8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(studentPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(studentPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(studentPane9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(listButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(deleteButton)
                                .addGap(10, 10, 10)
                                .addComponent(updateButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(insertButton)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(studentPane2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(studentPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(studentPane9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(studentPane8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(46, 46, 46)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(deleteButton)
                                        .addComponent(updateButton)
                                        .addComponent(insertButton)
                                        .addComponent(listButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void insertButtonActionPerformed(java.awt.event.ActionEvent evt) {
        if (!timeSlotId.getText().equals("") && !day.getText().equals("") && !startTime.getText().equals("") &&
                !endTime.getText().equals("")) {
            instanceOfDB.insertTimeSlot(Integer.parseInt(timeSlotId.getText()), day.getText(), startTime.getText(), endTime.getText());
            timeSlotId.setText("");
            day.setText("");
            startTime.setText("");
            endTime.setText("");
        }

    }

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {
        if (timeSlotId.getText().equals("")) {
            instanceOfDB.updateTimeSlot(0, day.getText(), startTime.getText(), endTime.getText());
            timeSlotId.setText("");
            day.setText("");
            startTime.setText("");
            endTime.setText("");
        } else {
            instanceOfDB.updateTimeSlot(Integer.parseInt(timeSlotId.getText()), day.getText(), startTime.getText(), endTime.getText());
            timeSlotId.setText("");
            day.setText("");
            startTime.setText("");
            endTime.setText("");
        }
    }

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {
        if (!timeSlotId.getText().equals("") && !day.getText().equals("")) {
            instanceOfDB.deleteTimeSlot(Integer.parseInt(timeSlotId.getText()), day.getText());
            timeSlotId.setText("");
            day.setText("");
            startTime.setText("");
            endTime.setText("");
        } else {
            JOptionPane.showMessageDialog(null, "Id and Day Fields Must Not Be Left Empty!");
        }


    }

    private void listButtonActionPerformed(java.awt.event.ActionEvent evt) {
        if (timeSlotId.getText().equals("") && day.getText().equals("") && startTime.getText().equals("") &&
                endTime.getText().equals("")) {
            instanceOfDB.selectAllTimeSlots(table.getTable());
            table.getTypeLabel().setText("All Time Slots");
            table.getTypeLabel().setBounds(490, 18, 90, 28);
            table.getTypeTextField().setVisible(false);
            table.setVisible(true);
            timeSlotId.setText("");
            day.setText("");
            startTime.setText("");
            endTime.setText("");
        }


    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InsertTimeSlots.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InsertTimeSlots.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InsertTimeSlots.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsertTimeSlots.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InsertTimeSlots().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField day;
    private javax.swing.JButton deleteButton;
    private javax.swing.JTextField endTime;
    private javax.swing.JButton insertButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton listButton;
    private javax.swing.JTextField startTime;
    private javax.swing.JLabel studentNameLabel;
    private javax.swing.JLabel studentNameLabel3;
    private javax.swing.JLabel studentNameLabel4;
    private javax.swing.JPanel studentPane;
    private javax.swing.JPanel studentPane2;
    private javax.swing.JPanel studentPane8;
    private javax.swing.JPanel studentPane9;
    private javax.swing.JLabel studentRegLabel;
    private javax.swing.JTextField timeSlotId;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
