/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dbproject;

import javax.swing.*;

/**
 * @author Mutahhar BM
 */
public class InsertStudent extends javax.swing.JFrame {
    FromDB instanceOfDB = new FromDB();
    TableUI table = new TableUI();

    /**
     * Creates new form InsertStudent
     */
    public InsertStudent() {
        initComponents();
        instanceOfDB.setConnection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        studentPane = new javax.swing.JPanel();
        studentRegLabel = new javax.swing.JLabel();
        studentReg = new javax.swing.JTextField();
        studentPane2 = new javax.swing.JPanel();
        studentNameLabel = new javax.swing.JLabel();
        studentName = new javax.swing.JTextField();
        studentPane8 = new javax.swing.JPanel();
        TotalCreditsLabel = new javax.swing.JLabel();
        totalCredits = new javax.swing.JTextField();
        studentPane9 = new javax.swing.JPanel();
        departmentLabel = new javax.swing.JLabel();
        department = new javax.swing.JTextField();
        insertButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        studentPane10 = new javax.swing.JPanel();
        studentNameLabel5 = new javax.swing.JLabel();
        semester = new javax.swing.JTextField();
        studentPane11 = new javax.swing.JPanel();
        studentNameLabel6 = new javax.swing.JLabel();
        section = new javax.swing.JTextField();
        studentPane12 = new javax.swing.JPanel();
        studentNameLabel7 = new javax.swing.JLabel();
        program = new javax.swing.JTextField();
        listButton = new javax.swing.JButton();
        studentPane1 = new javax.swing.JPanel();
        courseCodeLabel = new javax.swing.JLabel();
        courseCode = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Student");
        setAlwaysOnTop(true);

        studentPane.setLayout(null);

        studentRegLabel.setText("Student Reg:");
        studentPane.add(studentRegLabel);
        studentRegLabel.setBounds(0, 10, 80, 14);
        studentPane.add(studentReg);
        studentReg.setBounds(80, 7, 101, 28);

        studentPane2.setLayout(null);

        studentNameLabel.setText("Student Name:");
        studentPane2.add(studentNameLabel);
        studentNameLabel.setBounds(5, 10, 90, 14);
        studentPane2.add(studentName);
        studentName.setBounds(106, 7, 101, 28);

        TotalCreditsLabel.setText("Total Credits:");

        javax.swing.GroupLayout studentPane8Layout = new javax.swing.GroupLayout(studentPane8);
        studentPane8.setLayout(studentPane8Layout);
        studentPane8Layout.setHorizontalGroup(
                studentPane8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(studentPane8Layout.createSequentialGroup()
                                .addComponent(TotalCreditsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(totalCredits, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );
        studentPane8Layout.setVerticalGroup(
                studentPane8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(studentPane8Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(studentPane8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(TotalCreditsLabel)
                                        .addComponent(totalCredits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
        );

        departmentLabel.setText("Department Name:");

        javax.swing.GroupLayout studentPane9Layout = new javax.swing.GroupLayout(studentPane9);
        studentPane9.setLayout(studentPane9Layout);
        studentPane9Layout.setHorizontalGroup(
                studentPane9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(studentPane9Layout.createSequentialGroup()
                                .addComponent(departmentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(department, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                .addContainerGap())
        );
        studentPane9Layout.setVerticalGroup(
                studentPane9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(studentPane9Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(studentPane9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(departmentLabel)
                                        .addComponent(department, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        insertButton.setText("Insert");
        insertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertButtonActionPerformed(evt);
            }
        });

        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        studentPane10.setLayout(null);

        studentNameLabel5.setText("Semester:");
        studentPane10.add(studentNameLabel5);
        studentNameLabel5.setBounds(4, 14, 73, 14);
        studentPane10.add(semester);
        semester.setBounds(110, 10, 100, 25);

        studentNameLabel6.setText("Section:");

        javax.swing.GroupLayout studentPane11Layout = new javax.swing.GroupLayout(studentPane11);
        studentPane11.setLayout(studentPane11Layout);
        studentPane11Layout.setHorizontalGroup(
                studentPane11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(studentPane11Layout.createSequentialGroup()
                                .addComponent(studentNameLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(section, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        studentPane11Layout.setVerticalGroup(
                studentPane11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(studentPane11Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(studentPane11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(studentNameLabel6)
                                        .addComponent(section, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        studentNameLabel7.setText("Program:");

        javax.swing.GroupLayout studentPane12Layout = new javax.swing.GroupLayout(studentPane12);
        studentPane12.setLayout(studentPane12Layout);
        studentPane12Layout.setHorizontalGroup(
                studentPane12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(studentPane12Layout.createSequentialGroup()
                                .addComponent(studentNameLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(program, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        studentPane12Layout.setVerticalGroup(
                studentPane12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(studentPane12Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(studentPane12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(studentNameLabel7)
                                        .addComponent(program, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        listButton.setText("List");
        listButton.setMaximumSize(new java.awt.Dimension(65, 28));
        listButton.setMinimumSize(new java.awt.Dimension(65, 28));
        listButton.setPreferredSize(new java.awt.Dimension(65, 28));
        listButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listButtonActionPerformed(evt);
            }
        });

        courseCodeLabel.setText("Course Code:");

        javax.swing.GroupLayout studentPane1Layout = new javax.swing.GroupLayout(studentPane1);
        studentPane1.setLayout(studentPane1Layout);
        studentPane1Layout.setHorizontalGroup(
                studentPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(studentPane1Layout.createSequentialGroup()
                                .addComponent(courseCodeLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(courseCode, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );
        studentPane1Layout.setVerticalGroup(
                studentPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(studentPane1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(studentPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(courseCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(courseCodeLabel))
                                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addComponent(listButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(deleteButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(updateButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(insertButton)
                                .addGap(0, 90, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(studentPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(studentPane11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(studentPane12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(studentPane, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(24, 24, 24)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(studentPane9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(studentPane2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(studentPane10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(studentPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(studentPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(studentPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(studentPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(2, 2, 2)
                                                .addComponent(studentPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(studentPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(studentPane11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(studentPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(studentPane12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(listButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(updateButton)
                                                        .addComponent(insertButton))
                                                .addGap(36, 36, 36))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(deleteButton)
                                                .addGap(55, 55, 55))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void insertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertButtonActionPerformed
        // TODO add your handling code here:
        if (!studentReg.getText().equals("") && !studentName.getText().equals("") && !totalCredits.getText().equals("") &&
                !department.getText().equals("") && !section.getText().equals("") && !semester.getText().equals("") && !program.getText().equals("") &&
                !courseCode.getText().equals("")) {
            instanceOfDB.insertStudent(studentReg.getText(), studentName.getText(), Integer.parseInt(totalCredits.getText()),
                    department.getText(), section.getText(), Integer.parseInt(semester.getText()), program.getText(), courseCode.getText());
            studentReg.setText("");
            studentName.setText("");
            totalCredits.setText("");
            department.setText("");
            semester.setText("");
            section.setText("");
            program.setText("");
            courseCode.setText("");

        } else {
            JOptionPane.showMessageDialog(null, "All Fields must be filled!", "Error",
                    JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_insertButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
        if (totalCredits.getText().equals("") || semester.getText().equals("")) {
            if (totalCredits.getText().equals("") && semester.getText().equals("")) {
                instanceOfDB.updateStudent(studentReg.getText(), 0,
                        department.getText(), section.getText(), 0, program.getText(), courseCode.getText());
            }
           else if (totalCredits.getText().equals("")) {
                instanceOfDB.updateStudent(studentReg.getText(), 0,
                        department.getText(), section.getText(), Integer.parseInt(semester.getText()), program.getText(), courseCode.getText());
            } else if (semester.getText().equals("")) {
                instanceOfDB.updateStudent(studentReg.getText(), Integer.parseInt(totalCredits.getText()),
                        department.getText(), section.getText(), 0, program.getText(), courseCode.getText());
            }
        } else {
            instanceOfDB.updateStudent(studentReg.getText(), Integer.parseInt(totalCredits.getText()),
                    department.getText(), section.getText(), Integer.parseInt(semester.getText()), program.getText(), courseCode.getText());
        }
        studentReg.setText("");
        studentName.setText("");
        totalCredits.setText("");
        department.setText("");
        semester.setText("");
        section.setText("");
        program.setText("");
        courseCode.setText("");

    }

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        if (!studentReg.getText().equals("")) {
            instanceOfDB.deleteStudent(studentReg.getText());
            studentReg.setText("");
            studentName.setText("");
            totalCredits.setText("");
            department.setText("");
            semester.setText("");
            section.setText("");
            program.setText("");
            courseCode.setText("");
        }
        else{
            JOptionPane.showMessageDialog(null, "Student Registration must be filled!", "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    private void listButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listButtonActionPerformed
        if (studentName.getText().equals("") && studentReg.getText().equals("") && department.getText().equals("")
                && semester.getText().equals("") && section.getText().equals("") && program.getText().equals("") &&
                totalCredits.getText().equals("")) {
            instanceOfDB.selectAllStudents(table.getTable());
            table.getTypeLabel().setText("All Students");
            table.getTypeLabel().setBounds(490, 18, 90, 28);
            table.getTypeTextField().setVisible(false);
            table.setVisible(true);
            studentReg.setText("");
            studentName.setText("");
            totalCredits.setText("");
            department.setText("");
            semester.setText("");
            section.setText("");
            program.setText("");
            courseCode.setText("");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InsertStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InsertStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InsertStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsertStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InsertStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TotalCreditsLabel;
    private javax.swing.JTextField courseCode;
    private javax.swing.JLabel courseCodeLabel;
    private javax.swing.JButton deleteButton;
    private javax.swing.JTextField department;
    private javax.swing.JLabel departmentLabel;
    private javax.swing.JButton insertButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton listButton;
    private javax.swing.JTextField program;
    private javax.swing.JTextField section;
    private javax.swing.JTextField semester;
    private javax.swing.JTextField studentName;
    private javax.swing.JLabel studentNameLabel;
    private javax.swing.JLabel studentNameLabel5;
    private javax.swing.JLabel studentNameLabel6;
    private javax.swing.JLabel studentNameLabel7;
    private javax.swing.JPanel studentPane;
    private javax.swing.JPanel studentPane1;
    private javax.swing.JPanel studentPane10;
    private javax.swing.JPanel studentPane11;
    private javax.swing.JPanel studentPane12;
    private javax.swing.JPanel studentPane2;
    private javax.swing.JPanel studentPane8;
    private javax.swing.JPanel studentPane9;
    private javax.swing.JTextField studentReg;
    private javax.swing.JLabel studentRegLabel;
    private javax.swing.JTextField totalCredits;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
