/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dbproject;

import javax.swing.*;

/**
 *
 * @author Mutahhar BM
 */
public class InsertSection extends javax.swing.JFrame {
FromDB instanceOfDB = new FromDB();
    TableUI table = new TableUI();
    /**
     * Creates new form InsertStudent
     */
    public InsertSection() {
        initComponents();
        instanceOfDB.setConnection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        studentPane = new javax.swing.JPanel();
        studentRegLabel = new javax.swing.JLabel();
        section = new javax.swing.JTextField();
        studentPane2 = new javax.swing.JPanel();
        studentNameLabel = new javax.swing.JLabel();
        semester = new javax.swing.JTextField();
        studentPane8 = new javax.swing.JPanel();
        studentNameLabel3 = new javax.swing.JLabel();
        program = new javax.swing.JTextField();
        studentPane9 = new javax.swing.JPanel();
        studentNameLabel4 = new javax.swing.JLabel();
        department = new javax.swing.JTextField();
        insertButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        listButton = new javax.swing.JButton();
        studentPane10 = new javax.swing.JPanel();
        studentNameLabel8 = new javax.swing.JLabel();
        day = new javax.swing.JTextField();
        studentPane1 = new javax.swing.JPanel();
        studentRegLabel1 = new javax.swing.JLabel();
        timeSlotId = new javax.swing.JTextField();
        coursePane = new javax.swing.JPanel();
        courseCodeLabel = new javax.swing.JLabel();
        courseCode = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Section");
        setAlwaysOnTop(true);

        studentRegLabel.setText("Section:");

        javax.swing.GroupLayout studentPaneLayout = new javax.swing.GroupLayout(studentPane);
        studentPane.setLayout(studentPaneLayout);
        studentPaneLayout.setHorizontalGroup(
            studentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentPaneLayout.createSequentialGroup()
                .addComponent(studentRegLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(section, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        studentPaneLayout.setVerticalGroup(
            studentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(studentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(section, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(studentRegLabel))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        studentNameLabel.setText("Semester:");

        javax.swing.GroupLayout studentPane2Layout = new javax.swing.GroupLayout(studentPane2);
        studentPane2.setLayout(studentPane2Layout);
        studentPane2Layout.setHorizontalGroup(
            studentPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentPane2Layout.createSequentialGroup()
                .addComponent(studentNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(semester, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        studentPane2Layout.setVerticalGroup(
            studentPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(studentPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(studentNameLabel)
                    .addComponent(semester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        studentNameLabel3.setText("Program:");

        javax.swing.GroupLayout studentPane8Layout = new javax.swing.GroupLayout(studentPane8);
        studentPane8.setLayout(studentPane8Layout);
        studentPane8Layout.setHorizontalGroup(
            studentPane8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentPane8Layout.createSequentialGroup()
                .addComponent(studentNameLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(program, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        studentPane8Layout.setVerticalGroup(
            studentPane8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentPane8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(studentPane8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(studentNameLabel3)
                    .addComponent(program, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        studentNameLabel4.setText("Department Name:");

        javax.swing.GroupLayout studentPane9Layout = new javax.swing.GroupLayout(studentPane9);
        studentPane9.setLayout(studentPane9Layout);
        studentPane9Layout.setHorizontalGroup(
            studentPane9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentPane9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(studentNameLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(department, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3))
        );
        studentPane9Layout.setVerticalGroup(
            studentPane9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentPane9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(studentPane9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(studentNameLabel4)
                    .addComponent(department, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        insertButton.setText("Insert");
        insertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertButtonActionPerformed(evt);
            }
        });

        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        listButton.setText("List");
        listButton.setMaximumSize(new java.awt.Dimension(65, 28));
        listButton.setMinimumSize(new java.awt.Dimension(65, 28));
        listButton.setPreferredSize(new java.awt.Dimension(65, 28));
        listButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listButtonActionPerformed(evt);
            }
        });

        studentNameLabel8.setText("Day:");

        day.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                day5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout studentPane10Layout = new javax.swing.GroupLayout(studentPane10);
        studentPane10.setLayout(studentPane10Layout);
        studentPane10Layout.setHorizontalGroup(
            studentPane10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentPane10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(studentNameLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(day, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        studentPane10Layout.setVerticalGroup(
            studentPane10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentPane10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(studentPane10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(day, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(studentNameLabel8))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        studentRegLabel1.setText("TimeSlot Id:");

        timeSlotId.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout studentPane1Layout = new javax.swing.GroupLayout(studentPane1);
        studentPane1.setLayout(studentPane1Layout);
        studentPane1Layout.setHorizontalGroup(
            studentPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentPane1Layout.createSequentialGroup()
                .addComponent(studentRegLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(timeSlotId, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        studentPane1Layout.setVerticalGroup(
            studentPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentPane1Layout.createSequentialGroup()
                .addGroup(studentPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(studentPane1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(studentRegLabel1))
                    .addGroup(studentPane1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(timeSlotId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        courseCodeLabel.setText("Course Code:");

        javax.swing.GroupLayout coursePaneLayout = new javax.swing.GroupLayout(coursePane);
        coursePane.setLayout(coursePaneLayout);
        coursePaneLayout.setHorizontalGroup(
            coursePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(coursePaneLayout.createSequentialGroup()
                .addComponent(courseCodeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(courseCode)
                .addContainerGap())
        );
        coursePaneLayout.setVerticalGroup(
            coursePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(coursePaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(coursePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(courseCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(courseCodeLabel))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(listButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deleteButton)
                        .addGap(10, 10, 10)
                        .addComponent(updateButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(insertButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(coursePane, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(studentPane8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(studentPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(studentPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(studentPane9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(studentPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(studentPane10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(studentPane2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(studentPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(studentPane8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(studentPane9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(studentPane10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(studentPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(coursePane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteButton)
                    .addComponent(updateButton)
                    .addComponent(insertButton)
                    .addComponent(listButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void insertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertButtonActionPerformed
        // TODO add your handling code here:
         if (!semester.getText().equals("") && !section.getText().equals("") && !program.getText().equals("") &&
                !department.getText().equals("") && !timeSlotId.getText().equals("") && !day.getText().equals("") && !courseCode.getText().equals("")) {
            instanceOfDB.insertSection(section.getText(), Integer.parseInt(semester.getText()), program.getText(),
                    department.getText(), Integer.parseInt(timeSlotId.getText()), day.getText(),courseCode.getText());
            semester.setText("");
            section.setText("");
            program.setText("");
            department.setText("");
            timeSlotId.setText("");
            day.setText("");

        }
         //Insert Section timeslot
      else if (!semester.getText().equals("") && !section.getText().equals("") && !program.getText().equals("") &&
                department.getText().equals("") && !timeSlotId.getText().equals("") && !day.getText().equals("") && !courseCode.getText().equals("")) {
            instanceOfDB.insertSection(section.getText(), Integer.parseInt(semester.getText()), program.getText(),
                    department.getText(), Integer.parseInt(timeSlotId.getText()), day.getText(),courseCode.getText());
            semester.setText("");
            section.setText("");
            program.setText("");
            department.setText("");
            timeSlotId.setText("");
            day.setText("");
             courseCode.setText("");

        }
         else {
            JOptionPane.showMessageDialog(null, "All Fields must be filled!", "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_insertButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
         if (semester.getText().equals("") || timeSlotId.getText().equals("")) {
            if (semester.getText().equals("") && timeSlotId.getText().equals("")){
                instanceOfDB.updateSection(section.getText(), 0, program.getText(),
                        department.getText(), 0, day.getText(),courseCode.getText());
            }
            else if (semester.getText().equals("")){
                instanceOfDB.updateSection(section.getText(), 0, program.getText(),
                        department.getText(), Integer.parseInt(timeSlotId.getText()), day.getText(),courseCode.getText());
            }
            else if(timeSlotId.getText().equals("")){
                instanceOfDB.updateSection(section.getText(), Integer.parseInt(semester.getText()), program.getText(),
                        department.getText(), 0, day.getText(),courseCode.getText());
            }
        }
        else {
            instanceOfDB.updateSection(section.getText(), Integer.parseInt(semester.getText()), program.getText(),
                    department.getText(), Integer.parseInt(timeSlotId.getText()), day.getText(),courseCode.getText());
        }
        semester.setText("");
        section.setText("");
        program.setText("");
        department.setText("");
        timeSlotId.setText("");
        day.setText("");
        courseCode.setText("");
    }//GEN-LAST:event_updateButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        if (!semester.getText().equals("") && !section.getText().equals("") && !program.getText().equals("") && courseCode.getText().equals("")) {
            instanceOfDB.deleteSection(section.getText(), Integer.parseInt(semester.getText()), program.getText());
            semester.setText("");
            section.setText("");
            program.setText("");
            department.setText("");
            timeSlotId.setText("");
            day.setText("");
            courseCode.setText("");
        }
        else if (!semester.getText().equals("") && !section.getText().equals("") && !program.getText().equals("") && !courseCode.getText().equals("")) {
            instanceOfDB.deleteSectionTimeSlot(section.getText(), Integer.parseInt(semester.getText()), program.getText(),courseCode.getText());
            semester.setText("");
            section.setText("");
            program.setText("");
            department.setText("");
            timeSlotId.setText("");
            day.setText("");
            courseCode.setText("");
        }

        else {
            JOptionPane.showMessageDialog(null, "Section ID, Semester, and Program must not be empty!",
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void listButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listButtonActionPerformed
        // TODO add your handling code here:
        if (semester.getText().equals("") && section.getText().equals("") && program.getText().equals("") &&
                department.getText().equals("") && timeSlotId.getText().equals("") && day.getText().equals("")) {
            instanceOfDB.selectAllSection(table.getTable());
            table.getTypeLabel().setText("All Sections");
            table.getTypeLabel().setBounds(490, 18, 90, 28);
            table.getTypeTextField().setVisible(false);
            table.setVisible(true);
            semester.setText("");
            section.setText("");
            program.setText("");
            department.setText("");
            timeSlotId.setText("");
            day.setText("");
        }
        
    }//GEN-LAST:event_listButtonActionPerformed

    private void day5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_day5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_day5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InsertSection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InsertSection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InsertSection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsertSection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InsertSection().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField courseCode;
    private javax.swing.JLabel courseCodeLabel;
    private javax.swing.JPanel coursePane;
    private javax.swing.JTextField day;
    private javax.swing.JButton deleteButton;
    private javax.swing.JTextField department;
    private javax.swing.JButton insertButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton listButton;
    private javax.swing.JTextField program;
    private javax.swing.JTextField section;
    private javax.swing.JTextField semester;
    private javax.swing.JLabel studentNameLabel;
    private javax.swing.JLabel studentNameLabel3;
    private javax.swing.JLabel studentNameLabel4;
    private javax.swing.JLabel studentNameLabel8;
    private javax.swing.JPanel studentPane;
    private javax.swing.JPanel studentPane1;
    private javax.swing.JPanel studentPane10;
    private javax.swing.JPanel studentPane2;
    private javax.swing.JPanel studentPane8;
    private javax.swing.JPanel studentPane9;
    private javax.swing.JLabel studentRegLabel;
    private javax.swing.JLabel studentRegLabel1;
    private javax.swing.JTextField timeSlotId;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
